### ISSUE TITLE
Error .get()

### ISSUE THREAD

**Issue by pedrofelipest** [vishal-android-freak/firebase-micropython-esp32#2]
```
import ufirebase as firebase
URL = 'lucid-lychee'
print(firebase.get(URL))

```

Error in get()
Methods not exists

**Comment by gepd** [comment]
I've solve this calling to `firebaseURL` 

```python
import ufirebase as firebase
URL = firebase.firebaseURL('lucid-lychee')
print(firebase.get(URL))
```

You can replace the line 124 in `ufirebase.py` by `response = requests.get(firebaseURL(URL))` then you wont need to manually add the `firebaseURL`

**Comment by vishal-android-freak** [comment]
Fixed it!
