### ISSUE TITLE
Missing LICENSE file?

### ISSUE THREAD

**Issue by paulreimer** [vishal-android-freak/firebase-micropython-esp32#4]
I am wondering what the license of the software in this library is (hopefully open-source). The default GitHub policy is (non open-source):

> without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

https://help.github.com/articles/licensing-a-repository/

**Comment by vishal-android-freak** [comment]
Added it!. Yes it is open source :)
